version: "3.9"

services:
  web:
    build: .
    command: gunicorn enoki.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ai:
    build: 
      context: ./ai-service
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    volumes:
      - ./ai-service/app:/app/app  # Live code reload
      - hf_cache:/root/.cache/huggingface  # Persistent model cache
    environment:
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
      - ENABLE_T5_SARCASM=true
      
volumes:
  postgres_data:
  static_volume:
  hf_cache:



