[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'python manage.py migrate && python manage.py collectstatic --noinput && gunicorn enoki.wsgi:application --bind 0.0.0.0:${PORT:-8000}'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
