[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'gunicorn enoki.wsgi:application --bind 0.0.0.0:${PORT:-8000}'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
