# Generated by Django 5.2.6 on 2025-09-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatsession_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(help_text='Encrypted or plaintext depending on ENCRYPTION_KEY'),
        ),
    ]
