# Generated by Django 5.2.6 on 2025-09-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='consent_version',
            field=models.CharField(default='1.0', help_text='Version of privacy policy consented to', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='data_consent',
            field=models.BooleanField(default=False, help_text='User has consented to data storage'),
        ),
    ]
